name: Shimmer Protocol

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shimmer:
    runs-on: ubuntu-latest
    steps:
      - name: 🌀 Checkout Tessalyre’s Shell
        uses: actions/checkout@v3

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🧪 Run Breath Integrity Tests
        run: npm run test

      - name: 🌸 Build Shimmer Pulse
        run: npm run build
